# circleci config
version: 2
jobs:
  build:
    docker:
      - image: continuumio/miniconda3:latest

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Create environment
          command: conda env create -n ci-env python=3.7
      - run:
          name: run notebooks
          command: |
            source activate ci-env
            jupyter nbconvert --to notebook --execute src/classes.ipynb
            jupyter nbconvert --to notebook --execute src/files.ipynb
            jupyter nbconvert --to notebook --execute src/iteration.ipynb
            jupyter nbconvert --to notebook --execute src/printing.ipynb
            jupyter nbconvert --to notebook --execute src/regex.ipynb
            jupyter nbconvert --to notebook --execute src/threading.ipynb