# circleci config
version: 2
jobs:
  build:
    docker:
      - image: continuumio/miniconda3:latest

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Create environment
          command: conda create -n ci-env python=3.7 jupyter mypy
      - run:
          name: run notebooks
          command: |
            source activate ci-env
            jupyter nbconvert --to notebook --execute ipynb/classes.ipynb
            jupyter nbconvert --to notebook --execute ipynb/files.ipynb
            jupyter nbconvert --to notebook --execute ipynb/iteration.ipynb
            jupyter nbconvert --to notebook --execute ipynb/printing.ipynb
            jupyter nbconvert --to notebook --execute ipynb/regex.ipynb
            jupyter nbconvert --to notebook --execute ipynb/threading.ipynb
      - run:
          name: mypy checks
          command: |
            source activate ci-env
            mypy py/types.py
      - run:
          name: doctest
          command: |
            source activate ci-env
            python -m doctest py/types.py